# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceTCC2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.stackedWidget.setStyleSheet("background-color: #1e1e1e;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btn_sobre = QtWidgets.QPushButton(self.page)
        self.btn_sobre.setGeometry(QtCore.QRect(640, 30, 131, 51))
        self.btn_sobre.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_sobre.setObjectName("btn_sobre")
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setGeometry(QtCore.QRect(390, 160, 191, 22))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5a5a5a;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #2d2d2d;\n"
"    border-left: 1px solid #3a3a3a;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(180, 160, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label.setObjectName("label")
        self.btn_conectar = QtWidgets.QPushButton(self.page)
        self.btn_conectar.setGeometry(QtCore.QRect(300, 250, 191, 101))
        self.btn_conectar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_conectar.setObjectName("btn_conectar")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(260, 40, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 180, 161, 111))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_4.setGeometry(QtCore.QRect(432, 180, 161, 111))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.btn_voltarINICIO = QtWidgets.QPushButton(self.page_6)
        self.btn_voltarINICIO.setGeometry(QtCore.QRect(562, 477, 141, 41))
        self.btn_voltarINICIO.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_voltarINICIO.setObjectName("btn_voltarINICIO")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(240, 40, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 70, 531, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_garraAbrir = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_garraAbrir.setFont(font)
        self.btn_garraAbrir.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_garraAbrir.setObjectName("btn_garraAbrir")
        self.gridLayout.addWidget(self.btn_garraAbrir, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.btn_garraFechar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_garraFechar.setFont(font)
        self.btn_garraFechar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_garraFechar.setObjectName("btn_garraFechar")
        self.gridLayout.addWidget(self.btn_garraFechar, 0, 2, 1, 1)
        self.btn_pulsoAntiHora = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_pulsoAntiHora.setFont(font)
        self.btn_pulsoAntiHora.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_pulsoAntiHora.setObjectName("btn_pulsoAntiHora")
        self.gridLayout.addWidget(self.btn_pulsoAntiHora, 1, 1, 1, 1)
        self.btn_pulsoHora = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_pulsoHora.setFont(font)
        self.btn_pulsoHora.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_pulsoHora.setObjectName("btn_pulsoHora")
        self.gridLayout.addWidget(self.btn_pulsoHora, 1, 2, 1, 1)
        self.btn_linhaDireita = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_linhaDireita.setFont(font)
        self.btn_linhaDireita.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_linhaDireita.setObjectName("btn_linhaDireita")
        self.gridLayout.addWidget(self.btn_linhaDireita, 6, 2, 1, 1)
        self.btn_cotoveloTras = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_cotoveloTras.setFont(font)
        self.btn_cotoveloTras.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_cotoveloTras.setObjectName("btn_cotoveloTras")
        self.gridLayout.addWidget(self.btn_cotoveloTras, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.btn_pulsoFrente = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_pulsoFrente.setFont(font)
        self.btn_pulsoFrente.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_pulsoFrente.setObjectName("btn_pulsoFrente")
        self.gridLayout.addWidget(self.btn_pulsoFrente, 2, 2, 1, 1)
        self.btn_pulsoTras = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_pulsoTras.setFont(font)
        self.btn_pulsoTras.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_pulsoTras.setObjectName("btn_pulsoTras")
        self.gridLayout.addWidget(self.btn_pulsoTras, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.btn_ombroTras = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_ombroTras.setFont(font)
        self.btn_ombroTras.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_ombroTras.setObjectName("btn_ombroTras")
        self.gridLayout.addWidget(self.btn_ombroTras, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.btn_linhaEsquerda = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_linhaEsquerda.setFont(font)
        self.btn_linhaEsquerda.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_linhaEsquerda.setObjectName("btn_linhaEsquerda")
        self.gridLayout.addWidget(self.btn_linhaEsquerda, 6, 1, 1, 1)
        self.btn_cotoveloFrente = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_cotoveloFrente.setFont(font)
        self.btn_cotoveloFrente.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_cotoveloFrente.setObjectName("btn_cotoveloFrente")
        self.gridLayout.addWidget(self.btn_cotoveloFrente, 3, 2, 1, 1)
        self.btn_baseAntiHora = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_baseAntiHora.setFont(font)
        self.btn_baseAntiHora.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_baseAntiHora.setObjectName("btn_baseAntiHora")
        self.gridLayout.addWidget(self.btn_baseAntiHora, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14pt;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.btn_baseHora = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_baseHora.setFont(font)
        self.btn_baseHora.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_baseHora.setObjectName("btn_baseHora")
        self.gridLayout.addWidget(self.btn_baseHora, 5, 2, 1, 1)
        self.btn_ombroFrente = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_ombroFrente.setFont(font)
        self.btn_ombroFrente.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_ombroFrente.setObjectName("btn_ombroFrente")
        self.gridLayout.addWidget(self.btn_ombroFrente, 4, 1, 1, 1)
        self.btn_resetar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_resetar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_resetar.setObjectName("btn_resetar")
        self.gridLayout.addWidget(self.btn_resetar, 7, 1, 1, 1)
        self.btn_voltar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_voltar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_voltar.setObjectName("btn_voltar")
        self.gridLayout.addWidget(self.btn_voltar, 7, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(290, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 341, 541))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #111111;      /* fundo escuro, combina com o resto da tela */\n"
"    color: #ffffff;                 /* texto branco */\n"
"    border: 1px solid #3a3a3a;      /* borda sutil e técnica */\n"
"    border-radius: 6px;             /* cantos levemente arredondados */\n"
"    font-family: \'Consolas\';        /* fonte técnica tipo terminal */\n"
"    font-size: 12pt;                /* tamanho legível */\n"
"    padding: 6px;                   /* espaço interno para o texto não encostar nas bordas */\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid #8ab4f8;      /* destaque azul quando selecionado */\n"
"    background-color: #1a1a1a;      /* leve mudança no foco */\n"
"}")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.page_3)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 60, 401, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_salvar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_salvar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.btn_carregar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_carregar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_carregar.setObjectName("btn_carregar")
        self.horizontalLayout.addWidget(self.btn_carregar)
        self.btn_executar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_executar.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_executar.setObjectName("btn_executar")
        self.horizontalLayout.addWidget(self.btn_executar)
        self.btn_ajuda = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_ajuda.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_ajuda.setObjectName("btn_ajuda")
        self.horizontalLayout.addWidget(self.btn_ajuda)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 450, 195, 46))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_resetar_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_resetar_2.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_resetar_2.setObjectName("btn_resetar_2")
        self.horizontalLayout_2.addWidget(self.btn_resetar_2)
        self.btn_voltar2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_voltar2.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_voltar2.setObjectName("btn_voltar2")
        self.horizontalLayout_2.addWidget(self.btn_voltar2)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(460, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(110, 50, 571, 491))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    border: 2px solid #3a3a3a;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12pt;\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.btn_voltar3 = QtWidgets.QPushButton(self.page_4)
        self.btn_voltar3.setGeometry(QtCore.QRect(690, 490, 111, 41))
        self.btn_voltar3.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_voltar3.setObjectName("btn_voltar3")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(330, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page_5)
        self.textBrowser_6.setGeometry(QtCore.QRect(70, 50, 661, 471))
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    border: 2px solid #3a3a3a;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12pt;\n"
"}")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.btn_voltar4 = QtWidgets.QPushButton(self.page_5)
        self.btn_voltar4.setEnabled(True)
        self.btn_voltar4.setGeometry(QtCore.QRect(610, 460, 101, 41))
        self.btn_voltar4.setStyleSheet("QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    color: #ffffff;\n"
"    border: 2px solid #5e5e5e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #242424;\n"
"}")
        self.btn_voltar4.setObjectName("btn_voltar4")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(360, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\';\n"
"}")
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sobre.setText(_translate("MainWindow", "Sobre"))
        self.label.setText(_translate("MainWindow", "Porta do arduino:"))
        self.btn_conectar.setText(_translate("MainWindow", "Conectar"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Conexão com o Arduino</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Manual"))
        self.pushButton_4.setText(_translate("MainWindow", "Automático"))
        self.btn_voltarINICIO.setText(_translate("MainWindow", "Voltar"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Escolha o modo de controle</span></p></body></html>"))
        self.btn_garraAbrir.setText(_translate("MainWindow", "←"))
        self.label_8.setText(_translate("MainWindow", "Giro do Pulso:"))
        self.btn_garraFechar.setText(_translate("MainWindow", "→"))
        self.btn_pulsoAntiHora.setText(_translate("MainWindow", "←"))
        self.btn_pulsoHora.setText(_translate("MainWindow", "→"))
        self.btn_linhaDireita.setText(_translate("MainWindow", "→"))
        self.btn_cotoveloTras.setText(_translate("MainWindow", "←"))
        self.label_5.setText(_translate("MainWindow", "Movimento do Pulso:"))
        self.btn_pulsoFrente.setText(_translate("MainWindow", "→"))
        self.btn_pulsoTras.setText(_translate("MainWindow", "←"))
        self.label_4.setText(_translate("MainWindow", "Cotovelo:"))
        self.label_6.setText(_translate("MainWindow", "Garra:"))
        self.label_3.setText(_translate("MainWindow", "Ombro:"))
        self.btn_ombroTras.setText(_translate("MainWindow", "→"))
        self.label_7.setText(_translate("MainWindow", "Linha transversal:"))
        self.btn_linhaEsquerda.setText(_translate("MainWindow", "←"))
        self.btn_cotoveloFrente.setText(_translate("MainWindow", "→"))
        self.btn_baseAntiHora.setText(_translate("MainWindow", "←"))
        self.label_2.setText(_translate("MainWindow", "Base:"))
        self.btn_baseHora.setText(_translate("MainWindow", "→"))
        self.btn_ombroFrente.setText(_translate("MainWindow", "←"))
        self.btn_resetar.setText(_translate("MainWindow", "Resetar"))
        self.btn_voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Controle Manual</span></p></body></html>"))
        self.btn_salvar.setText(_translate("MainWindow", "Salvar"))
        self.btn_carregar.setText(_translate("MainWindow", "Carregar"))
        self.btn_executar.setText(_translate("MainWindow", "Executar"))
        self.btn_ajuda.setText(_translate("MainWindow", "Ajuda"))
        self.btn_resetar_2.setText(_translate("MainWindow", "Resetar"))
        self.btn_voltar2.setText(_translate("MainWindow", "Voltar"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Controle automático</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- BXX Movimento da base</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- OXX Movimento do ombro</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- CXX Movimento do cotovelo</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- MPXX Movimento do pulso</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- GPXX Giro do pulso</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- GXX Abrir e fechar garra</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- LTXX Linha tranversal</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">- Z retornar pra posição zero</span></p></body></html>"))
        self.btn_voltar3.setText(_translate("MainWindow", "Voltar"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Comandos</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Interface de controle de braço robótico criado para trabalho de conclusão de curso do ano de 2025 do Colégio Técnico Industrial de Guaratinguetá Professor Carlos Augusto Patrício Amorim.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Criadores: Caio Vianna Guimarães Galvão, Clara Fernandes de Oliveira, Davi Nascimento Gomes, Jõao Luis Garufe Coelho e João Pedro Soares.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Alunos do curso de automação industrial</span></p></body></html>"))
        self.btn_voltar4.setText(_translate("MainWindow", "Voltar"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Sobre</span></p></body></html>"))
